# Generated by Django 6.0.3 on 2026-04-06 05:29

import django.core.serializers.json
import django.db.models.deletion
import djangocms_frontend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuminaFrontendBaseModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('ui_item', models.CharField(max_length=30)),
                ('tag_type', djangocms_frontend.fields.TagTypeField(blank=True, default='div', help_text='Select the HTML tag to be used.', max_length=255, verbose_name='Tag type')),
                ('config', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
