# Generated by Django 6.0.3 on 2026-04-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('lumina_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('pretitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CoursesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('greeting', models.CharField(blank=True, max_length=255)),
                ('next_class', models.CharField(blank=True, max_length=255)),
                ('stat_1_title', models.CharField(blank=True, max_length=64)),
                ('stat_1_value', models.CharField(blank=True, max_length=64)),
                ('stat_2_title', models.CharField(blank=True, max_length=64)),
                ('stat_2_value', models.CharField(blank=True, max_length=64)),
                ('stat_3_title', models.CharField(blank=True, max_length=64)),
                ('stat_3_value', models.CharField(blank=True, max_length=64)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EnrollmentModal',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subtext', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('content', models.TextField(blank=True, help_text='Footer HTML (Tailwind allowed)')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.TextField(blank=True)),
                ('subheading', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=128)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=1024)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('content', models.TextField(blank=True, help_text='Navigation HTML (use Tailwind classes)')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
